export const fishes = [
  { nombre: "Acedia", index: 1, url: "1_acedia.pdf" },
  { nombre: "Aguja", index: 2, url: "2_aguja.pdf" },
  { nombre: "Aguja blanca", index: 3, url: "3_aguja_blanca.pdf" },
  { nombre: "Aligote", index: 4, url: "4_aligote.pdf" },
  { nombre: "Alosa", index: 5, url: "5_alosa_spp.pdf" },
  { nombre: "Atun blanco", index: 6, url: "6_atun_blanco.pdf" },
  { nombre: "Atun rojo", index: 7, url: "7_atun_rojo.pdf" },
  { nombre: "Bacaladilla", index: 8, url: "8_bacaladilla.pdf" },
  { nombre: "Boga", index: 9, url: "9_boga.pdf" },
  { nombre: "Besugo", index: 10, url: "10_besugo.pdf" },
  { nombre: "Boquerón", index: 11, url: "11_boqueron.pdf" },
  { nombre: "Breca", index: 12, url: "12_breca.pdf" },
  { nombre: "Caballa", index: 13, url: "13_caballa.pdf" },
  {
    nombre: "Caballas/Estorninos",
    index: 14,
    url: "14_caballas_estorninos.pdf",
  },
  { nombre: "Capellán", index: 15, url: "15_capellan.pdf" },
  { nombre: "Caramel", index: 16, url: "16_caramel.pdf" },
  { nombre: "Cherna", index: 17, url: "17_cherna.pdf" },
  { nombre: "Chopa", index: 18, url: "18_chopa.pdf" },
  { nombre: "Congrio", index: 19, url: "19_congrio.pdf" },
  { nombre: "Dorada", index: 20, url: "20_dorada.pdf" },
  { nombre: "Estornino", index: 21, url: "21_estornino.pdf" },
  { nombre: "Faneca", index: 22, url: "22_faneca.pdf" },
  { nombre: "Gallo", index: 23, url: "23_gallos.pdf" },
  { nombre: "Herrera", index: 24, url: "24_herrera.pdf" },
  { nombre: "Japuta", index: 25, url: "25_japuta.pdf" },
  { nombre: "Jurel", index: 26, url: "26_jurel.pdf" },
  { nombre: "Lenguado europeo", index: 27, url: "27_lenguado_europeo.pdf" },
  { nombre: "Lubina", index: 28, url: "28_lubina.pdf" },
  { nombre: "Marlín azul", index: 29, url: "29_martlin?azul.pdf" },
  { nombre: "Merluza", index: 30, url: "30_merluza.pdf" },
  { nombre: "Meros", index: 31, url: "31_meros.pdf" },
  { nombre: "Mielga", index: 32, url: "32_mielga.pdf" },
  { nombre: "Mújol", index: 33, url: "33_mujoles.pdf" },
  { nombre: "Mojarra", index: 34, url: "34_mojarra.pdf" },
  { nombre: "Pargo", index: 35, url: "35_pargo.pdf" },
  { nombre: "Patudo", index: 36, url: "36_patudo.pdf" },
  { nombre: "Pez cinto", index: 37, url: "37_pez_cinto.pdf" },
  { nombre: "Pez espada", index: 38, url: "38_pez_espada.pdf" },
  { nombre: "Pintarroja", index: 39, url: "39_pintarrojas.pdf" },
  { nombre: "Platija", index: 40, url: "40_platija.pdf" },
  { nombre: "Rabil-Atun de aleta amarilla", index: 41, url: "41_rabil.pdf" },
  { nombre: "Rape", index: 42, url: "42_rapes.pdf" },
  { nombre: "Raspallón", index: 43, url: "43_raspallon.pdf" },
  { nombre: "Rayas", index: 44, url: "44_rayas.pdf" },
  { nombre: "Remol", index: 45, url: "45_remol.pdf" },
  { nombre: "Rodaballo", index: 46, url: "46_rodaballo.pdf" },
  { nombre: "Rubios", index: 47, url: "47_rubios.pdf" },
  { nombre: "Salema", index: 48, url: "48_salema.pdf" },
  { nombre: "Salmonete de fango", index: 49, url: "49_salmonete_de_fango.pdf" },
  { nombre: "Salmonete de roca", index: 50, url: "50_salmonete_de_roca.pdf" },
  { nombre: "Sardina", index: 51, url: "51_sardina.pdf" },
  { nombre: "Sargo", index: 52, url: "52_sargopdf" },
  { nombre: "Sargo breado", index: 53, url: "53_sargo_breado.pdf" },
  { nombre: "Sargo picudo", index: 54, url: "54_sargo_picudo.pdf" },
];
